# Generated by Django 4.2.26 on 2025-11-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model3d', '0003_alter_model3d_model_url_alter_model3d_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='gaussian_model_url',
            field=models.FileField(blank=True, help_text='가우시안 스플래팅 PLY 파일', null=True, upload_to='gaussian/'),
        ),
    ]
