# Generated by Django 4.2.26 on 2025-11-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model3d', '0004_model3d_gaussian_model_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='model_url',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
